name: Push to Github registry

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
        
     - name: Log in to the Container registry
       uses: docker/login-action@ec9cdf07d570632daeb912f5b2099cb9ec1d01e6
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: ghcr.io/qjoly/nix-maintainers-get-packages
  run_action:
    needs: build
    runs-on: ubuntu-latest
    name: Run nix-maintainers-get-packages
    steps:
      - uses: actions/checkout@v3
        with:
          path: './nixpkgs'
          repository: 'NixOS/nixpkgs'
      
      - uses: actions/checkout@v3
      
      - name: debug
        run: |
          ls -lah
          ls -lah ./nixpkgs
          grep -r "qjoly" ./nixpkgs/pkgs
      
      - name: Run nix-maintainers-get-packages
        uses: qjoly/nix-maintainers-get-packages@v0.1.1
        with:
          file: './test.md'
          path_nixpkgs: './nixpkgs/pkgs'
          maintainer: 'qjoly'
