name: Push to Github registry

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
        
     - name: Log in to the Container registry
       uses: docker/login-action@ec9cdf07d570632daeb912f5b2099cb9ec1d01e6
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: ghcr.io/qjoly/nix-maintainers-get-packages
  run_action:
    needs: build
    runs-on: ubuntu-latest
    name: Run nix-maintainers-get-packages
    steps:
      - uses: actions/checkout@v3
        with:
          path: './nixpkgs'
          repository: 'NixOS/nixpkgs'
      
      - uses: actions/checkout@v3
      
      - name: Run nix-maintainers-get-packages
        uses: qjoly/nix-maintainers-get-packages@v0.1.1
        with:
          file: './test.md'
          path_nixpkgs: './nixpkgs/pkgs'
          maintainer: 'qjoly'
          
      - name: Push changes if needed
        run: |
          git add test.md
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name "GitHub Actions[Bot]"
          # Push only if README.md has been modified
          if [[ $(git status --porcelain "test.md" | wc -l) -gt 0 ]]; then git commit -m "[BOT] Update test.md"; git push; fi
