name: Run action on test.md

on:
  push:
    branches:
      - main
jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Run 'Nix-Maintened_by'
    steps:
      - uses: actions/checkout@v3 # Clone your code
      
      - uses: actions/checkout@v3 # Clone NixPkgs
        with:
          path: './nixpkgs'
          repository: 'NixOS/nixpkgs'
      
      - name: Run nix-maintainers-get-packages # Run action 
        uses: qjoly/nix-maintainers-get-packages@v0.1.3
        with:
          file: './test.md'
          path_nixpkgs: './nixpkgs/pkgs'
          maintainer: 'qjoly'
