name: Test
on:
  push:
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Run nix-maintainers-get-packages
    steps:
      - uses: actions/checkout@v3
        with:
          path: '/tmp/nixpkgs'
          repository: 'NixOS/nixpkgs'
      - name: Run nix-maintainers-get-packages
        uses: qjoly/nix-maintainers-get-packages@v0.1
        with:
          file: './test.md'
          path_nixpkgs: '/tmp/nixpkgs'
          maintainer: 'qjoly'
