name: Run action on test.md

on:
  push:
    branches:
      - main
jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Run 'Nix-Maintained_by'
    steps:
      - uses: actions/checkout@v4 # Clone your code
      
      - uses: actions/checkout@v4 # Clone NixPkgs
        with:
          path: './nixpkgs'
          repository: 'NixOS/nixpkgs'
      
      - name: Run nix-maintainers-get-packages # Run action 
        uses: qjoly/Nix-Maintained_by@v0.2.0
        with:
          file: './test.md'
          path_nixpkgs: './nixpkgs/pkgs'
          maintainer: 'qjoly'
